import type { IceCreamFlavor } from '@/types';

export const placeholderFlavors: IceCreamFlavor[] = [
  {
    id: '1',
    name: 'Vanilla Bean Bliss',
    description: 'Classic rich vanilla bean ice cream, smooth and creamy.',
    price: 4.99,
    image: 'https://placehold.co/600x400.png',
    category: 'Cups',
    rating: 4.5,
    stock: 100,
    aiPromptHint: 'vanilla icecream',
  },
  {
    id: '2',
    name: 'Chocolate Decadence',
    description: 'Deep, dark chocolate indulgence for true chocoholics.',
    price: 5.49,
    image: 'https://placehold.co/600x400.png',
    category: 'Cups',
    rating: 4.8,
    stock: 80,
    aiPromptHint: 'chocolate icecream',
  },
  {
    id: '3',
    name: 'Strawberry Swirl Sensation',
    description: 'Sweet strawberries swirled into creamy goodness.',
    price: 5.29,
    image: 'https://placehold.co/600x400.png',
    category: 'Tricone',
    rating: 4.6,
    stock: 90,
    aiPromptHint: 'strawberry icecream',
  },
  {
    id: '4',
    name: 'Minty Choco Chip',
    description: 'Refreshing mint ice cream with generous chocolate chips.',
    price: 5.49,
    image: 'https://placehold.co/600x400.png',
    category: 'Tubs',
    rating: 4.7,
    stock: 70,
    aiPromptHint: 'mint chocolatechip',
  },
  {
    id: '5',
    name: 'Caramel Crunch Delight',
    description: 'Smooth caramel ice cream with crunchy toffee pieces.',
    price: 5.99,
    image: 'https://placehold.co/600x400.png',
    category: 'Jumbo Cups',
    rating: 4.9,
    stock: 60,
    aiPromptHint: 'caramel icecream',
  },
  {
    id: '6',
    name: 'Cookies & Cream Dream',
    description: 'Classic cookies and cream, a fan favorite.',
    price: 5.49,
    image: 'https://placehold.co/600x400.png',
    category: 'Packs',
    rating: 4.7,
    stock: 120,
    aiPromptHint: 'cookies cream',
  },
  {
    id: '7',
    name: 'Peanut Butter Passion',
    description: 'Creamy peanut butter ice cream with chocolate swirls.',
    price: 5.79,
    image: 'https://placehold.co/600x400.png',
    category: 'Sticks',
    rating: 4.6,
    stock: 50,
    aiPromptHint: 'peanutbutter icecream',
  },
  {
    id: '8',
    name: 'Mango Tango Sorbet',
    description: 'Refreshing and tangy mango sorbet, dairy-free.',
    price: 4.99,
    image: 'https://placehold.co/600x400.png',
    category: 'Cups',
    rating: 4.4,
    stock: 75,
    aiPromptHint: 'mango sorbet',
  },
];
