import type { IceCreamFlavor } from '@/types';

export const placeholderFlavors: IceCreamFlavor[] = [
  // Cups
  {
    id: '1',
    name: 'Vanilla Bean Bliss Cup',
    description: 'Classic rich vanilla bean ice cream in a convenient cup.',
    price: 180,
    image: 'https://placehold.co/600x400.png',
    category: 'Cups',
    rating: 4.5,
    stock: 100,
    aiPromptHint: 'vanilla icecream cup',
  },
  {
    id: '2',
    name: 'Chocolate Decadence Cup',
    description: 'Deep, dark chocolate indulgence in a personal cup.',
    price: 200,
    image: 'https://placehold.co/600x400.png',
    category: 'Cups',
    rating: 4.8,
    stock: 80,
    aiPromptHint: 'chocolate icecream cup',
  },
  {
    id: '8',
    name: 'Mango Tango Sorbet Cup',
    description: 'Refreshing and tangy mango sorbet, dairy-free, in a cup.',
    price: 170,
    image: 'https://placehold.co/600x400.png',
    category: 'Cups',
    rating: 4.4,
    stock: 75,
    aiPromptHint: 'mango sorbet cup',
  },
  {
    id: '9',
    name: 'Kesar Pista Delight Cup',
    description: 'Traditional Indian saffron and pistachio flavored ice cream cup.',
    price: 220,
    image: 'https://placehold.co/600x400.png',
    category: 'Cups',
    rating: 4.7,
    stock: 65,
    aiPromptHint: 'kesar pista icecream',
  },

  // Cones
  {
    id: '3',
    name: 'Strawberry Swirl Cone',
    description: 'Sweet strawberries swirled into creamy goodness, served in a crispy cone.',
    price: 190,
    image: 'https://placehold.co/600x400.png',
    category: 'Cones',
    rating: 4.6,
    stock: 90,
    aiPromptHint: 'strawberry icecream cone',
  },
  {
    id: '10',
    name: 'Butterscotch Crunch Cone',
    description: 'Rich butterscotch ice cream with crunchy pralines in a cone.',
    price: 200,
    image: 'https://placehold.co/600x400.png',
    category: 'Cones',
    rating: 4.5,
    stock: 85,
    aiPromptHint: 'butterscotch icecream cone',
  },
  {
    id: '11',
    name: 'Choco-Vanilla Twister Cone',
    description: 'A delightful twist of chocolate and vanilla soft serve in a cone.',
    price: 175,
    image: 'https://placehold.co/600x400.png',
    category: 'Cones',
    rating: 4.3,
    stock: 95,
    aiPromptHint: 'chocolate vanilla cone',
  },

  // Tubs
  {
    id: '4',
    name: 'Minty Choco Chip Tub',
    description: 'Refreshing mint ice cream with generous chocolate chips, in a shareable tub.',
    price: 450, // Larger size, higher price
    image: 'https://placehold.co/600x400.png',
    category: 'Tubs',
    rating: 4.7,
    stock: 70,
    aiPromptHint: 'mint chocolatechip tub',
  },
  {
    id: '12',
    name: 'Belgian Chocolate Fantasy Tub',
    description: 'Luxurious Belgian chocolate ice cream for the ultimate indulgence (500ml tub).',
    price: 550,
    image: 'https://placehold.co/600x400.png',
    category: 'Tubs',
    rating: 4.9,
    stock: 50,
    aiPromptHint: 'belgian chocolate tub',
  },
  {
    id: '13',
    name: 'Alphonso Mango Magic Tub',
    description: 'Rich and creamy ice cream made with real Alphonso mango pulp (500ml tub).',
    price: 500,
    image: 'https://placehold.co/600x400.png',
    category: 'Tubs',
    rating: 4.8,
    stock: 60,
    aiPromptHint: 'alphonso mango tub',
  },

  // Sticks
  {
    id: '7',
    name: 'Peanut Butter Passion Stick',
    description: 'Creamy peanut butter ice cream with chocolate swirls on a stick.',
    price: 150,
    image: 'https://placehold.co/600x400.png',
    category: 'Sticks',
    rating: 4.6,
    stock: 50,
    aiPromptHint: 'peanutbutter icecream stick',
  },
  {
    id: '14',
    name: 'Orange Burst Kulfi Stick',
    description: 'Tangy orange flavored traditional Indian kulfi on a stick.',
    price: 120,
    image: 'https://placehold.co/600x400.png',
    category: 'Sticks',
    rating: 4.3,
    stock: 110,
    aiPromptHint: 'orange kulfi stick',
  },
  {
    id: '15',
    name: 'Double Chocolate Fudge Stick',
    description: 'Rich chocolate ice cream coated in chocolate and fudge ripple, on a stick.',
    price: 160,
    image: 'https://placehold.co/600x400.png',
    category: 'Sticks',
    rating: 4.7,
    stock: 70,
    aiPromptHint: 'chocolate fudge stick',
  },
  
  // Family Packs
  {
    id: '6',
    name: 'Cookies & Cream Dream Pack',
    description: 'Classic cookies and cream, a fan favorite, in a family pack (1L).',
    price: 600,
    image: 'https://placehold.co/600x400.png',
    category: 'Family Packs',
    rating: 4.7,
    stock: 120,
    aiPromptHint: 'cookies cream pack',
  },
  {
    id: '5', // Re-categorized
    name: 'Caramel Crunch Delight Pack',
    description: 'Smooth caramel ice cream with crunchy toffee pieces in a family pack (1L).',
    price: 650,
    image: 'https://placehold.co/600x400.png',
    category: 'Family Packs',
    rating: 4.9,
    stock: 60,
    aiPromptHint: 'caramel icecream pack',
  },
  {
    id: '16',
    name: 'Tutti Frutti Carnival Pack',
    description: 'A delightful mix of candied fruits in creamy ice cream, family pack (1L).',
    price: 580,
    image: 'https://placehold.co/600x400.png',
    category: 'Family Packs',
    rating: 4.4,
    stock: 80,
    aiPromptHint: 'tuttifrutti icecream pack',
  },

  // Sorbets (Dairy-Free)
  {
    id: '17',
    name: 'Lemon Zest Sorbet',
    description: 'Tangy and refreshing lemon sorbet, a perfect palate cleanser.',
    price: 160, // Cup size
    image: 'https://placehold.co/600x400.png',
    category: 'Sorbets',
    rating: 4.5,
    stock: 70,
    aiPromptHint: 'lemon sorbet',
  },
  {
    id: '18',
    name: 'Raspberry Rhapsody Sorbet',
    description: 'Vibrant and fruity raspberry sorbet, bursting with flavor.',
    price: 175, // Cup size
    image: 'https://placehold.co/600x400.png',
    category: 'Sorbets',
    rating: 4.6,
    stock: 60,
    aiPromptHint: 'raspberry sorbet',
  },
];
